on: [push]

name: Golang Shorten URL

jobs:
  # setup-server:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Azure Login
  #       uses: azure/login@v1
  #       with:
  #         creds: ${{ secrets.AZURE_CREDENTIALS }}

  #     - name: Delete Record Set
  #       run: |
  #         IP=$(az vm show -d -g int492 -n shorten-url --query publicIps -o tsv)
  #         az network dns record-set a remove-record \
  #           --ipv4-address $IP \
  #           --record-set-name @ \
  #           --resource-group int492 \
  #           --zone-name a7.tnpl.me --yes
  #       continue-on-error: true

  #     - name: Clear VM
  #       run: |
  #         az vm delete -g int492 -n shorten-url --yes
  #       continue-on-error: true

  #     - name: Create VM
  #       run: |
  #         echo ${{secrets.SSH_KEY}} > ssh.pub
  #         az vm create \
  #           --resource-group int492 \
  #           --name shorten-url \
  #           --image Canonical:UbuntuServer:16.04-LTS:latest \
  #           --authentication-type all \
  #           --admin-username azureproject \
  #           --admin-password Azureuser123 \
  #           --attach-data-disks DataDisk_0 \
  #           --size Standard_B1s \
  #           --output none \
  #           --ssh-key-values ssh.pub \
  #           --verbose

  #     - name: Add record set
  #       run: |
  #         IP=$(az vm show -d -g int492 -n shorten-url --query publicIps -o tsv)
  #         az network dns record-set a add-record \
  #           --ipv4-address ${IP} \
  #           --record-set-name @ \
  #           --resource-group int492 \
  #           --zone-name a7.tnpl.me \
  #           --ttl 300 -o none

  #     - name: Allow HTTP
  #       run: |
  #         az network nsg rule create \
  #           --resource-group int492 \
  #           --nsg-name shorten-urlNSG \
  #           --name Port_8000 \
  #           --protocol tcp \
  #           --priority 1010 \
  #           --destination-port-range 8000

  setup-environment:
    runs-on: ubuntu-latest
    # needs: [setup-server]

    steps:
      - name: Setup Environment
        uses: appleboy/ssh-action@master
        with:
          host: a7.tnpl.me
          username: azureproject #${{ secrets.SSH_USERNAME }}
          password: Azureuser123 #${{ secrets.SSH_PASSWORD }}
          script: |
            # Firewall Config
            sudo ufw allow ssh
            sudo ufw enable

            # sudo apt-get update -y

            # # Install Golang
            # wget https://dl.google.com/go/go1.15.8.linux-amd64.tar.gz
            # sudo tar -xvf go1.15.8.linux-amd64.tar.gz
            # sudo mv go /usr/local

            # export GOROOT=/usr/local/go
            # export GOPATH=$HOME/Projects/ADMFactory/Golang
            # export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

            # vi ~/.profile

            # go version

            # sudo apt-get -y install git

            # git clone https://github.com/shin-iji/go-shorten-url.git
